/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ConsoleImport } from "./routes/console";
import { Route as IndexImport } from "./routes/index";
import { Route as ConsoleVenuesImport } from "./routes/console/venues";
import { Route as ConsoleGamesImport } from "./routes/console/games";
import { Route as ConsoleDashboardImport } from "./routes/console/dashboard";
import { Route as ConsoleCompetitionsImport } from "./routes/console/competitions";
import { Route as AuthLoginImport } from "./routes/auth/login";
import { Route as ConsoleVenuesIndexImport } from "./routes/console/venues.index";
import { Route as ConsoleGamesIndexImport } from "./routes/console/games.index";
import { Route as ConsoleCompetitionsIndexImport } from "./routes/console/competitions.index";
import { Route as ConsoleVenuesVenueIdImport } from "./routes/console/venues.$venueId";
import { Route as ConsoleGamesGameIdImport } from "./routes/console/games.$gameId";

// Create/Update Routes

const ConsoleRoute = ConsoleImport.update({
  id: "/console",
  path: "/console",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ConsoleVenuesRoute = ConsoleVenuesImport.update({
  id: "/venues",
  path: "/venues",
  getParentRoute: () => ConsoleRoute,
} as any);

const ConsoleGamesRoute = ConsoleGamesImport.update({
  id: "/games",
  path: "/games",
  getParentRoute: () => ConsoleRoute,
} as any);

const ConsoleDashboardRoute = ConsoleDashboardImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => ConsoleRoute,
} as any);

const ConsoleCompetitionsRoute = ConsoleCompetitionsImport.update({
  id: "/competitions",
  path: "/competitions",
  getParentRoute: () => ConsoleRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRoute,
} as any);

const ConsoleVenuesIndexRoute = ConsoleVenuesIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ConsoleVenuesRoute,
} as any);

const ConsoleGamesIndexRoute = ConsoleGamesIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ConsoleGamesRoute,
} as any);

const ConsoleCompetitionsIndexRoute = ConsoleCompetitionsIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ConsoleCompetitionsRoute,
} as any);

const ConsoleVenuesVenueIdRoute = ConsoleVenuesVenueIdImport.update({
  id: "/$venueId",
  path: "/$venueId",
  getParentRoute: () => ConsoleVenuesRoute,
} as any);

const ConsoleGamesGameIdRoute = ConsoleGamesGameIdImport.update({
  id: "/$gameId",
  path: "/$gameId",
  getParentRoute: () => ConsoleGamesRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/console": {
      id: "/console";
      path: "/console";
      fullPath: "/console";
      preLoaderRoute: typeof ConsoleImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof rootRoute;
    };
    "/console/competitions": {
      id: "/console/competitions";
      path: "/competitions";
      fullPath: "/console/competitions";
      preLoaderRoute: typeof ConsoleCompetitionsImport;
      parentRoute: typeof ConsoleImport;
    };
    "/console/dashboard": {
      id: "/console/dashboard";
      path: "/dashboard";
      fullPath: "/console/dashboard";
      preLoaderRoute: typeof ConsoleDashboardImport;
      parentRoute: typeof ConsoleImport;
    };
    "/console/games": {
      id: "/console/games";
      path: "/games";
      fullPath: "/console/games";
      preLoaderRoute: typeof ConsoleGamesImport;
      parentRoute: typeof ConsoleImport;
    };
    "/console/venues": {
      id: "/console/venues";
      path: "/venues";
      fullPath: "/console/venues";
      preLoaderRoute: typeof ConsoleVenuesImport;
      parentRoute: typeof ConsoleImport;
    };
    "/console/games/$gameId": {
      id: "/console/games/$gameId";
      path: "/$gameId";
      fullPath: "/console/games/$gameId";
      preLoaderRoute: typeof ConsoleGamesGameIdImport;
      parentRoute: typeof ConsoleGamesImport;
    };
    "/console/venues/$venueId": {
      id: "/console/venues/$venueId";
      path: "/$venueId";
      fullPath: "/console/venues/$venueId";
      preLoaderRoute: typeof ConsoleVenuesVenueIdImport;
      parentRoute: typeof ConsoleVenuesImport;
    };
    "/console/competitions/": {
      id: "/console/competitions/";
      path: "/";
      fullPath: "/console/competitions/";
      preLoaderRoute: typeof ConsoleCompetitionsIndexImport;
      parentRoute: typeof ConsoleCompetitionsImport;
    };
    "/console/games/": {
      id: "/console/games/";
      path: "/";
      fullPath: "/console/games/";
      preLoaderRoute: typeof ConsoleGamesIndexImport;
      parentRoute: typeof ConsoleGamesImport;
    };
    "/console/venues/": {
      id: "/console/venues/";
      path: "/";
      fullPath: "/console/venues/";
      preLoaderRoute: typeof ConsoleVenuesIndexImport;
      parentRoute: typeof ConsoleVenuesImport;
    };
  }
}

// Create and export the route tree

interface ConsoleCompetitionsRouteChildren {
  ConsoleCompetitionsIndexRoute: typeof ConsoleCompetitionsIndexRoute;
}

const ConsoleCompetitionsRouteChildren: ConsoleCompetitionsRouteChildren = {
  ConsoleCompetitionsIndexRoute: ConsoleCompetitionsIndexRoute,
};

const ConsoleCompetitionsRouteWithChildren =
  ConsoleCompetitionsRoute._addFileChildren(ConsoleCompetitionsRouteChildren);

interface ConsoleGamesRouteChildren {
  ConsoleGamesGameIdRoute: typeof ConsoleGamesGameIdRoute;
  ConsoleGamesIndexRoute: typeof ConsoleGamesIndexRoute;
}

const ConsoleGamesRouteChildren: ConsoleGamesRouteChildren = {
  ConsoleGamesGameIdRoute: ConsoleGamesGameIdRoute,
  ConsoleGamesIndexRoute: ConsoleGamesIndexRoute,
};

const ConsoleGamesRouteWithChildren = ConsoleGamesRoute._addFileChildren(
  ConsoleGamesRouteChildren,
);

interface ConsoleVenuesRouteChildren {
  ConsoleVenuesVenueIdRoute: typeof ConsoleVenuesVenueIdRoute;
  ConsoleVenuesIndexRoute: typeof ConsoleVenuesIndexRoute;
}

const ConsoleVenuesRouteChildren: ConsoleVenuesRouteChildren = {
  ConsoleVenuesVenueIdRoute: ConsoleVenuesVenueIdRoute,
  ConsoleVenuesIndexRoute: ConsoleVenuesIndexRoute,
};

const ConsoleVenuesRouteWithChildren = ConsoleVenuesRoute._addFileChildren(
  ConsoleVenuesRouteChildren,
);

interface ConsoleRouteChildren {
  ConsoleCompetitionsRoute: typeof ConsoleCompetitionsRouteWithChildren;
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute;
  ConsoleGamesRoute: typeof ConsoleGamesRouteWithChildren;
  ConsoleVenuesRoute: typeof ConsoleVenuesRouteWithChildren;
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleCompetitionsRoute: ConsoleCompetitionsRouteWithChildren,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleGamesRoute: ConsoleGamesRouteWithChildren,
  ConsoleVenuesRoute: ConsoleVenuesRouteWithChildren,
};

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/console": typeof ConsoleRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/console/competitions": typeof ConsoleCompetitionsRouteWithChildren;
  "/console/dashboard": typeof ConsoleDashboardRoute;
  "/console/games": typeof ConsoleGamesRouteWithChildren;
  "/console/venues": typeof ConsoleVenuesRouteWithChildren;
  "/console/games/$gameId": typeof ConsoleGamesGameIdRoute;
  "/console/venues/$venueId": typeof ConsoleVenuesVenueIdRoute;
  "/console/competitions/": typeof ConsoleCompetitionsIndexRoute;
  "/console/games/": typeof ConsoleGamesIndexRoute;
  "/console/venues/": typeof ConsoleVenuesIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/console": typeof ConsoleRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/console/dashboard": typeof ConsoleDashboardRoute;
  "/console/games/$gameId": typeof ConsoleGamesGameIdRoute;
  "/console/venues/$venueId": typeof ConsoleVenuesVenueIdRoute;
  "/console/competitions": typeof ConsoleCompetitionsIndexRoute;
  "/console/games": typeof ConsoleGamesIndexRoute;
  "/console/venues": typeof ConsoleVenuesIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/console": typeof ConsoleRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/console/competitions": typeof ConsoleCompetitionsRouteWithChildren;
  "/console/dashboard": typeof ConsoleDashboardRoute;
  "/console/games": typeof ConsoleGamesRouteWithChildren;
  "/console/venues": typeof ConsoleVenuesRouteWithChildren;
  "/console/games/$gameId": typeof ConsoleGamesGameIdRoute;
  "/console/venues/$venueId": typeof ConsoleVenuesVenueIdRoute;
  "/console/competitions/": typeof ConsoleCompetitionsIndexRoute;
  "/console/games/": typeof ConsoleGamesIndexRoute;
  "/console/venues/": typeof ConsoleVenuesIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/console"
    | "/auth/login"
    | "/console/competitions"
    | "/console/dashboard"
    | "/console/games"
    | "/console/venues"
    | "/console/games/$gameId"
    | "/console/venues/$venueId"
    | "/console/competitions/"
    | "/console/games/"
    | "/console/venues/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/console"
    | "/auth/login"
    | "/console/dashboard"
    | "/console/games/$gameId"
    | "/console/venues/$venueId"
    | "/console/competitions"
    | "/console/games"
    | "/console/venues";
  id:
    | "__root__"
    | "/"
    | "/console"
    | "/auth/login"
    | "/console/competitions"
    | "/console/dashboard"
    | "/console/games"
    | "/console/venues"
    | "/console/games/$gameId"
    | "/console/venues/$venueId"
    | "/console/competitions/"
    | "/console/games/"
    | "/console/venues/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ConsoleRoute: typeof ConsoleRouteWithChildren;
  AuthLoginRoute: typeof AuthLoginRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/console",
        "/auth/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/console": {
      "filePath": "console.tsx",
      "children": [
        "/console/competitions",
        "/console/dashboard",
        "/console/games",
        "/console/venues"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/console/competitions": {
      "filePath": "console/competitions.tsx",
      "parent": "/console",
      "children": [
        "/console/competitions/"
      ]
    },
    "/console/dashboard": {
      "filePath": "console/dashboard.tsx",
      "parent": "/console"
    },
    "/console/games": {
      "filePath": "console/games.tsx",
      "parent": "/console",
      "children": [
        "/console/games/$gameId",
        "/console/games/"
      ]
    },
    "/console/venues": {
      "filePath": "console/venues.tsx",
      "parent": "/console",
      "children": [
        "/console/venues/$venueId",
        "/console/venues/"
      ]
    },
    "/console/games/$gameId": {
      "filePath": "console/games.$gameId.tsx",
      "parent": "/console/games"
    },
    "/console/venues/$venueId": {
      "filePath": "console/venues.$venueId.tsx",
      "parent": "/console/venues"
    },
    "/console/competitions/": {
      "filePath": "console/competitions.index.tsx",
      "parent": "/console/competitions"
    },
    "/console/games/": {
      "filePath": "console/games.index.tsx",
      "parent": "/console/games"
    },
    "/console/venues/": {
      "filePath": "console/venues.index.tsx",
      "parent": "/console/venues"
    }
  }
}
ROUTE_MANIFEST_END */
