name: Build images using Containerfile
on: [push]

jobs:
  build-client:
    name: Build client image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get timestamp
      id: get-timestamp
      run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Containerfile.client
        push: true
        tags: |
          roboticsoutreach/livecomp-client:latest
          roboticsoutreach/livecomp-client:${{ github.sha }}
          roboticsoutreach/livecomp-client:latest-${{ steps.get-timestamp.outputs.timestamp }}
        build-args: |
          API_SERVER_URL=https://api.comp.roboticsoutreach.org
          API_WS_URL=ws://api.comp.roboticsoutreach.org

  build-server:
    name: Build server image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get timestamp
      id: get-timestamp
      run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Containerfile.server
        push: true
        tags: |
          roboticsoutreach/livecomp-server:latest
          roboticsoutreach/livecomp-server:${{ github.sha }}
          roboticsoutreach/livecomp-server:latest-${{ steps.get-timestamp.outputs.timestamp }}

